### ISSUE TITLE
✘ [ERROR] Cannot start service: Host version "0.14.49" does not match binary version "0.14.47"

### ISSUE THREAD

**Issue by hanwenbo** [walrusjs/redbud#1]
项目装了loadsh type的库后
再运行redbud build 就会报错，其他的没改什么关键的 看不出什么影响的

尝试了删除node_modules、切换node版本均无效

```
> redbud build

✘ [ERROR] Cannot start service: Host version "0.14.49" does not match binary version "0.14.47"

1 error
error - Error: Parse config file failed: [/Users/name/javascript/utilsjs/packages/ui-mobile/.redbudrc.ts]
    at Function.getUserConfig (/Users/name/Library/pnpm/global/5/.pnpm/@umijs+core@4.0.11/node_modules/@umijs/core/dist/config/config.js:143:17)
    at Config.getUserConfig (/Users/name/Library/pnpm/global/5/.pnpm/@umijs+core@4.0.11/node_modules/@umijs/core/dist/config/config.js:51:19)
    at Service.run (/Users/name/Library/pnpm/global/5/.pnpm/@umijs+core@4.0.11/node_modules/@umijs/core/dist/service/service.js:195:37)
    at Service.run2 (/Users/name/Library/pnpm/global/5/.pnpm/redbud@1.0.0-beta.7_webpack@5.79.0/node_modules/redbud/dist/service/service.js:58:27)
    at Object.run (/Users/name/Library/pnpm/global/5/.pnpm/redbud@1.0.0-beta.7_webpack@5.79.0/node_modules/redbud/dist/cli/cli.js:30:23)
    at Object.<anonymous> (/Users/name/Library/pnpm/global/5/.pnpm/redbud@1.0.0-beta.7_webpack@5.79.0/node_modules/redbud/bin/redbud.js:5:4)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  [cause]: Error: Parse file failed: [/Users/name/javascript/utilsjs/packages/ui-mobile/.redbudrc.ts]
      at transform (/Users/name/Library/pnpm/global/5/.pnpm/@umijs+utils@4.0.11/node_modules/@umijs/utils/dist/register.js:49:11)
      at revert.ext (/Users/name/Library/pnpm/global/5/.pnpm/@umijs+utils@4.0.11/node_modules/@umijs/utils/dist/register.js:55:62)
      at Module._compile (/Users/name/Library/pnpm/global/5/.pnpm/@umijs+utils@4.0.11/node_modules/@umijs/utils/compiled/pirates/index.js:1:1671)
      at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
      at Object.newLoader [as .ts] (/Users/name/Library/pnpm/global/5/.pnpm/@umijs+utils@4.0.11/node_modules/@umijs/utils/compiled/pirates/index.js:1:1746)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (/Users/name/Library/pnpm/global/5/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
      at Function.getUserConfig (/Users/name/Library/pnpm/global/5/.pnpm/@umijs+core@4.0.11/node_modules/@umijs/core/dist/config/config.js:141:54) {
    [cause]: Error: The service was stopped
        at /Users/name/Library/pnpm/global/5/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.js:1381:29
        at /Users/name/Library/pnpm/global/5/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.js:666:9
        at Socket.afterClose (/Users/name/Library/pnpm/global/5/.pnpm/esbuild@0.14.49/node_modules/esbuild/lib/main.js:644:7)
        at Socket.emit (node:events:538:35)
        at endReadableNT (node:internal/streams/readable:1345:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
  }
}

```

**Comment by hanwenbo** [comment]
假如升级到node 18 倒是不提示  但redbud build 一直卡着无响应

**Comment by hanwenbo** [comment]
node 18 

pnpm  i redbud -g

解决了，或许是版本问题

- redbud 1.0.0-beta.7
+ redbud 1.6.0
